# Generated by Django 6.0.1 on 2026-04-16 23:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
                'db_table': 'personne',
            },
        ),
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'db_table': 'annee_scolaire',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=100, unique=True)),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'db_table': 'matiere',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('capacite', models.PositiveSmallIntegerField(default=0)),
                ('type_salle', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'db_table': 'salle',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eleve', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('matricule', models.CharField(blank=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'db_table': 'eleve',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enseignant', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialite', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('date_embauche', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'enseignant',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('profession', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personnel', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fonction', models.CharField(choices=[('direction', 'Direction'), ('administration', 'Administration'), ('scolarite', 'Scolarité'), ('finances', 'Finances')], max_length=20)),
                ('date_embauche', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
                'db_table': 'personnel',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(blank=True, max_length=50)),
                ('effectif_max', models.PositiveSmallIntegerField(default=40)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='classes', to='core.anneescolaire')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_heures_hebdo', models.PositiveSmallIntegerField(default=0)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cours', to='core.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cours', to='core.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cours', to='core.matiere')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'db_table': 'cours',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('table_cible', models.CharField(max_length=50)),
                ('id_enreg', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'action",
                'verbose_name_plural': 'Historique des actions',
                'db_table': 'historique_actions',
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('transfere', 'Transféré'), ('abandonne', 'Abandonné')], default='actif', max_length=10)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inscriptions', to='core.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inscriptions', to='core.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'inscription',
            },
        ),
        migrations.CreateModel(
            name='LienParentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lien', models.CharField(choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur', 'Tuteur'), ('tutrice', 'Tutrice'), ('autre', 'Autre')], max_length=10)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parents_lies', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='enfants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lien parent–élève',
                'verbose_name_plural': 'Liens parent–élève',
                'db_table': 'lien_parent_eleve',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('type_notif', models.CharField(choices=[('note_saisie', 'Note saisie'), ('absence_saisie', 'Absence saisie'), ('bulletin_genere', 'Bulletin généré'), ('annonce', 'Annonce générale')], max_length=20)),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classe')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type_periode', models.CharField(choices=[('trimestre', 'Trimestre'), ('semestre', 'Semestre')], max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cloturee', models.BooleanField(default=False)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='core.anneescolaire')),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
                'db_table': 'periode',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type_eval', models.CharField(choices=[('devoir_surveille', 'Devoir surveillé'), ('interrogation', 'Interrogation'), ('examen_semestriel', 'Examen semestriel')], max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=200)),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notes', to='core.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notes', to='core.periode')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('rang', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('appreciation', models.CharField(blank=True, max_length=300)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bulletins', to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bulletins', to='core.periode')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'db_table': 'bulletin',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('nb_heures', models.PositiveSmallIntegerField(default=1)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('justifiee', 'Justifiée'), ('non_justifiee', 'Non justifiée')], default='en_attente', max_length=15)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='absences', to=settings.AUTH_USER_MODEL)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='absences', to='core.cours')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='absences', to='core.periode')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'db_table': 'absence',
            },
        ),
        migrations.CreateModel(
            name='ResultatMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('rang', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resultats', to='core.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resultats', to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='resultats', to='core.periode')),
            ],
            options={
                'verbose_name': 'Résultat matière',
                'verbose_name_plural': 'Résultats matières',
                'db_table': 'resultat_matiere',
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='core.cours')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='creneaux', to='core.periode')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='creneaux', to='core.salle')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'db_table': 'emploi_du_temps',
            },
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('nom', 'annee'), name='unique_classe_par_annee'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('eleve', 'annee'), name='unique_eleve_par_annee'),
        ),
        migrations.AddConstraint(
            model_name='lienparenteleve',
            constraint=models.UniqueConstraint(fields=('parent', 'eleve'), name='unique_lien_parent_eleve'),
        ),
        migrations.AddConstraint(
            model_name='cours',
            constraint=models.UniqueConstraint(fields=('matiere', 'classe', 'annee'), name='unique_cours_matiere_classe_annee'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(condition=models.Q(('valeur__gte', 0), ('valeur__lte', 20)), name='note_valeur_entre_0_et_20'),
        ),
        migrations.AddConstraint(
            model_name='bulletin',
            constraint=models.UniqueConstraint(fields=('eleve', 'periode'), name='unique_bulletin_eleve_periode'),
        ),
        migrations.AddConstraint(
            model_name='resultatmatiere',
            constraint=models.UniqueConstraint(fields=('eleve', 'cours', 'periode'), name='unique_resultat_eleve_cours_periode'),
        ),
    ]
