# Generated by Django 6.0.1 on 2026-04-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bulletin_effectif_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='nom',
        ),
        migrations.AddField(
            model_name='salle',
            name='batiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salle',
            name='numero',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='salle',
            name='type_salle',
            field=models.CharField(choices=[('salle_de_cours', 'Salle de cours'), ('laboratoire', 'Laboratoire'), ('salle_informatique', 'Salle informatique'), ('gymnase', 'Gymnase')], default='salle_de_cours', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='emploidutemps',
            constraint=models.UniqueConstraint(fields=('salle', 'jour', 'heure_debut', 'periode'), name='unique_salle_creneau'),
        ),
    ]
