# Generated by Django 6.0.1 on 2026-04-18 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_salle_nom_salle_batiment_salle_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='cycle',
            field=models.CharField(choices=[('premier', 'Premier cycle'), ('second', 'Second cycle')], default='premier', max_length=10),
        ),
        migrations.AddField(
            model_name='classe',
            name='section',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='coefficient',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('note_saisie', 'Note saisie'), ('absence_enregistree', 'Absence enregistrée'), ('depassement_absences', 'Dépassement seuil absences'), ('bulletin_disponible', 'Bulletin disponible'), ('annonce', 'Annonce générale')], max_length=25),
        ),
        migrations.AlterField(
            model_name='salle',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
