# Generated by Django 6.0.1 on 2026-04-20 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_classe_cycle_classe_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('type_event', models.CharField(choices=[('vacances', 'Vacances scolaires'), ('examen', 'Examen / Évaluation'), ('reunion', 'Réunion'), ('ferie', 'Jour férié'), ('autre', 'Autre')], default='autre', max_length=15)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('annee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='core.anneescolaire')),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evenement_scolaire',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FraisScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_du', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('partiel', 'Partiellement payé')], default='en_attente', max_length=10)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='frais', to='core.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='frais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'frais_scolarite',
                'unique_together': {('eleve', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=150)),
                ('corps', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('recu_numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('mobile_money', 'Mobile Money')], default='especes', max_length=20)),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.fraisscolarite')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paiement',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
