# Generated by Django 6.0.4 on 2026-04-21 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evenementscolaire_fraisscolarite_message_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='core.anneescolaire')),
            ],
            options={
                'verbose_name': 'Tarif par niveau',
                'verbose_name_plural': 'Tarifs par niveau',
                'db_table': 'tarif_niveau',
                'unique_together': {('annee', 'niveau')},
            },
        ),
    ]
